Enable searches for fundingRounds
torch-ai/crunchbase-js pull request #19
Opened 2022-03-21 07:35 UTC by enricoros

In addition to organizations, people, and principals, this change enables searching for funding rounds.

Without this change, it would be hard to perform such a search as the axios client is private and not accessible
from downstream applications.

2022-03-22 13:43 UTC, lancegliser commented
I appreciate the pointer to what you need. I'll take a little bit to work on this. I can't accept this as written since there's no test associated yet. Would it be alright if I need a couple days with my existing work?

2022-03-22 13:44 UTC, lancegliser requested changes
Holding off on the PR until tests are added. Seeing if I can just get them in quickly given the seeds already here.

2022-03-22 14:00 UTC, lancegliser commented
Took just a couple minutes. I added this and a minor docs fix in #20. Thanks for the assist! Will publish a new version for you shortly.

2022-03-22 14:00 UTC, closed without merging

2022-03-23 05:14 UTC, enricoros commented
Thank you so much, this helps! I can remove the duplicate code I needed to make it work 👍